"""adds rental columns, FKs

Revision ID: 4ab64444b94e
Revises: 0fe54bc91c0e
Create Date: 2025-05-07 14:53:09.696049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab64444b94e'
down_revision = '0fe54bc91c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'video', ['video_id'], ['id'])
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('due_date')
        batch_op.drop_column('video_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
